name: "Check branch"

on:
  push:
    branches:
      - '**'        
      - '!main'

permissions: write-all

jobs:
  golint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  horusec:
    name: Security Analisys
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true"

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    needs: [golint, horusec]
    
    strategy:
      fail-fast: false
      matrix:
        goVersion: ['1.16', '1.17', '1.18', '1.19']
    
    steps:
    - name: Clone Repository 
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goVersion }}

    - name: Test
      run: go test -v ./...
  benchmark:
    name: Performance Regeression.
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      
      - name: Run benchmark
        run:  go test -bench 'Benchmark' ./... | tee output.txt
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '130%'
          # DO NOT PUSH BENCH DATA. This work belongs to main repository action
          auto-push: false
          # Break the pipilene on error
          fail-on-alert: true
